### PR TITLE
Feedback #1

### PR DESCRIPTION
**Pull request by ftomasul**
Completed exercise in branch titled "warmup1".

### CODE REVIEW

**Review by larskotthoff — CHANGES_REQUESTED** [review]
Looks like you forgot to upload code/report/etc.

**Comment by ftomasul** [comment]
All the files are in the warmup1 branch, should I put them in main?

**Comment by ftomasul** [comment]
I had accidentally removed the files from my branch somehow, my bad. It should be good now.

**Review by larskotthoff — CHANGES_REQUESTED** [review]
Looks like a good start -- can you also predict as a classification problem please?

**Review by larskotthoff — APPROVED** [review]

**Comment by larskotthoff** [comment]
Please don't merge any PRs ever...

**Comment by ftomasul** [comment]
Noted, my bad

**Pull request merged**
